######################################################################
# Automatically generated by qmake (2.00a) mar oct 10 22:44:41 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += .
INCLUDEPATH += . /home/bjobard/Softs/glm-0.4.1
QT += xml opengl

# Input
HEADERS += sample.h
SOURCES += main.cpp sample.cpp

LIBS += -lSDL
